"""init

Revision ID: 746b51249c1f
Revises: d6cb7e970828
Create Date: 2020-12-18 21:55:43.147680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746b51249c1f'
down_revision = 'd6cb7e970828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('state_code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state_code')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
