"""init

Revision ID: d6cb7e970828
Revises: 8e9c46887a13
Create Date: 2020-12-18 21:03:41.451836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cb7e970828'
down_revision = '8e9c46887a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite_stock', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorite_stock')
    # ### end Alembic commands ###
